# Prettier friendly markdownlint config (all formatting rules disabled)
extends: markdownlint/style/prettier
MD040: false
MD036: false
MD034: false
MD033: false
MD024: false
MD025: false
MD026: false
